title: Phillip Schneider
page-top-title: HOME
top-section-bg-text: Phillip Schneider <br> Head of Natural Language Processing <br> @ ALMA PHIL
home-subtitle: ABOUT ME
copyright-text: '&copy; Phillip Schneider 2025'
